#!/bin/bash

text() {
	cat /sys/class/power_supply/BAT1/capacity
}

class() {
  percent=$1
  # TODO: if battery is charging, and below 20, don't return 'low'
  if (( percent > 20 )); then
    cat /sys/class/power_supply/BAT1/status | tr [:upper:] [:lower:]
  else
    echo "low"
  fi
}

icon() {
  echo ""
}

text=$(text)
class=$(class $text)
icon=$(icon $text $class)

echo "{\"text\":\"$text%\",\"icon\":\"$icon\",\"class\":\"$class\"}"

