#! /bin/sh

killall eww
simple-bus -c

pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || $(~/.config/polybar/launch.sh --blocks) &

# eww daemon
# eww open bar
feh --bg-scale $HOME/Pictures/wallpapers/cliffs.jpg;

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color  '#32302f'
bspc config focused_border_color '#52504f'
bspc config border_width         3
bspc config window_gap           12

bspc config automatic_scheme     spiral
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



# bspc config focused_border_color '#cc241d' # red
# bspc config focused_border_color '#8ec07c' # aqua
# bspc config focused_border_color '#689d6a' # aqua 2
# bspc config focused_border_color '#b8bb26'
# bspc config focused_border_color '#fb4934' # bright red
# bspc config focused_border_color '#fe8019'
# bspc config focused_border_color '#d79921'
