#! /bin/sh

alias sxhkd="sxhkd -c $HOME/.config/bspwm/sxhkdrc"
alias EWW_SCRIPTS="$HOME/.config/eww/scripts"
alias eww-bar="eww -c $HOME/.config/eww/bar"

pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x sxhkd > /dev/null || sxhkd &
eww-bar daemon
eww-bar open main
feh --bg-scale $HOME/Pictures/wall.gif

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12

bspc config automatic_scheme     spiral
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
